# Generated by Django 2.2.3 on 2019-08-04 13:52

from django.db import migrations, models
import jobs.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='result',
            field=models.FileField(blank=True, null=True, upload_to=jobs.models.upload_path),
        ),
    ]
