# Generated by Django 2.2.3 on 2019-08-04 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20190804_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='job',
            name='name',
            field=models.CharField(default='entry', max_length=64),
            preserve_default=False,
        ),
    ]
