# Generated by Django 2.2.3 on 2019-08-06 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20190804_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='estimated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
